; https://github.com/ggml-org/llama.cpp/tree/master/tools/server#model-presets
; keys / values are the same as the command line arg name
; This is only for fields related to the models, non-model fields need to still be passed as CLI options
[*]
main-gpu = 0
parallel = 1
ubatch-size = 256
load-on-startup = false

[qwen38]
ctx-size = 85000
n-gpu-layers = all
model = qwen38/Qwen3.8-27B-GSQ-RCO-IQ3_S-mtp.gguf
mmproj = qwen38/mmproj-F16.gguf
tensor-split = 0.64,0.36
mmproj-device = none
spec-type = draft-mtp
spec-draft-n-max = 2
spec-draft-type-k = q4_0
spec-draft-type-v = q4_0
spec-draft-ngl = all

[qwen38-image]
ctx-size = 60000
n-gpu-layers = all
model = qwen38/Qwen3.8-27B-GSQ-RCO-IQ3_S-mtp.gguf
mmproj = qwen38/mmproj-F16.gguf
tensor-split = 0.7,0.3
mmproj-device = CUDA1
spec-type = draft-mtp
spec-draft-n-max = 2
spec-draft-type-k = q4_0
spec-draft-type-v = q4_0
spec-draft-ngl = all
