[aliases]
tug = ["bookmark", "advance", "--to", "@-"]
push = ["git", "push", "--bookmark"]

[revsets]
log = "all()"

[remotes.origin]
auto-track-bookmarks = "*"

[user]
name = "kingdomkind"
email = "kingdomkind@protonmail.com"
